name: Publish

on:
  workflow_dispatch: {}
  release:
    types:
      - created

env:
  PYTHON_VERSION: "3.12"

permissions:
  contents: read    # required for 'actions/checkout@v2'
  id-token: write  # required for 'Build and Publish'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build and Publish
        env:
          TIKIT_VERSION: ${{ github.event.release.tag_name }}
        run: |
          uv build
          uv publish
