name: Test

on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Package
        run: |
          uv pip install -e .[pycocotools,test]

      - name: Test
        run: |
          uv run ruff check .
          uv run pytest --cov --cov-report term-missing tests/ --cov-fail-under 80
          uv run mypy
